language: php
sudo: false

php: 5.5

mysql:
  database: og
  username: root
  encoding: utf8

before_script:
  # Remember the current rules test directory for later use in the Drupal
  # installation.
  - TESTDIR=$(pwd)
  # Navigate out of module directory to prevent blown stack by recursive module
  # lookup.
  - cd ..

  # Create database.
  - mysql -e 'create database og'
  # Download Drupal 8 core.
  - git clone --branch 8.0.x --depth 1 http://git.drupal.org/project/drupal.git
  - cd drupal

  - ln -s $TESTDIR modules/og

script:
  # Run the PHPUnit tests which also include the kernel tests.
  - ./vendor/phpunit/phpunit/phpunit -c ./core/phpunit.xml.dist ./modules/og
