language: php
sudo: false

php: 5.5

mysql:
  database: og
  username: root
  encoding: utf8

addons:
  apt:
    packages:
    - php5-cgi
    - php5-mysql

before_script:
  # Remember the current rules test directory for later use in the Drupal
  # installation.
  - TESTDIR=$(pwd)
  # Navigate out of module directory to prevent blown stack by recursive module
  # lookup.
  - cd ..

  # Update composer and drush.
  - sudo apt-get update & /dev/null
  - composer self-update
  - export PATH="$HOME/.composer/vendor/bin:$PATH"
  - composer global require drush/drush:dev-master

  # Create database.
  - mysql -e 'create database og'
  # Download Drupal 8 core.
  - git clone --branch 8.0.x --depth 1 http://git.drupal.org/project/drupal.git
  - cd drupal

  - ln -s $TESTDIR modules/og

  # Install drupal and OG
  - drush --verbose site-install --db-url=mysql://root:@127.0.0.1/og --yes
  - drush en simpletest og -y

  # Ensure the PHP environment is ready.
  - phpenv rehash

  # Start a web server.
  - drush runserver 127.0.0.1:8080 &
  - until netstat -an 2>/dev/null | grep '8080.*LISTEN'; do true; done

script:
  # Run the PHPUnit tests which also include the kernel tests.
  - ./vendor/phpunit/phpunit/phpunit -c ./core/phpunit.xml.dist ./modules/og

  # Run simple test.
  - php core/scripts/run-tests.sh --verbose --color --php `which php` --url http://127.0.0.1:8080 "og" | tee /tmp/test.txt; TEST_EXIT=${PIPESTATUS[0]}; echo $TEST_EXIT

